set_property IOSTANDARD LVCMOS33 [get_ports {an_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_out[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]


set_property PACKAGE_PIN R15 [get_ports {in[3]}]
set_property PACKAGE_PIN M13 [get_ports {in[2]}]
set_property PACKAGE_PIN L16 [get_ports {in[1]}]
set_property PACKAGE_PIN J15 [get_ports {in[0]}]

set_property PACKAGE_PIN V10 [get_ports {an_sel[7]}]
set_property PACKAGE_PIN U11 [get_ports {an_sel[6]}]
set_property PACKAGE_PIN U12 [get_ports {an_sel[5]}]
set_property PACKAGE_PIN H6 [get_ports {an_sel[4]}]
set_property PACKAGE_PIN T13 [get_ports {an_sel[3]}]
set_property PACKAGE_PIN R16 [get_ports {an_sel[2]}]
set_property PACKAGE_PIN U8 [get_ports {an_sel[1]}]
set_property PACKAGE_PIN T8 [get_ports {an_sel[0]}]

set_property PACKAGE_PIN U13 [get_ports {an_out[7]}]
set_property PACKAGE_PIN K2 [get_ports {an_out[6]}]
set_property PACKAGE_PIN T14 [get_ports {an_out[5]}]
set_property PACKAGE_PIN P14 [get_ports {an_out[4]}]
set_property PACKAGE_PIN J14 [get_ports {an_out[3]}]
set_property PACKAGE_PIN T9 [get_ports {an_out[2]}]
set_property PACKAGE_PIN J18 [get_ports {an_out[1]}]
set_property PACKAGE_PIN J17 [get_ports {an_out[0]}]

set_property PACKAGE_PIN T10 [get_ports {out[6]}]
set_property PACKAGE_PIN R10 [get_ports {out[5]}]
set_property PACKAGE_PIN K16 [get_ports {out[4]}]
set_property PACKAGE_PIN K13 [get_ports {out[3]}]
set_property PACKAGE_PIN P15 [get_ports {out[2]}]
set_property PACKAGE_PIN T11 [get_ports {out[1]}]
set_property PACKAGE_PIN L18 [get_ports {out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports dp]
set_property IOSTANDARD LVCMOS33 [get_ports dp_in]

set_property PACKAGE_PIN H15 [get_ports dp]
set_property PACKAGE_PIN N17 [get_ports dp_in]
